@echo off
setlocal disableDelayedExpansion

del Goodrich.log
del GoodrichTamassiaGoldwasserPages.aux
del GoodrichTamassiaGoldwasserPages.dvi
del GoodrichTamassiaGoldwasserPages.idv
del GoodrichTamassiaGoldwasserPages.lg
del GoodrichTamassiaGoldwasserPages.log
del GoodrichTamassiaGoldwasserPages.tmp
del GoodrichTamassiaGoldwasserPages.toc
del GoodrichTamassiaGoldwasserPages.xdv
del texput.log
